name: version-diff
on: 
  pull_request:
    paths: 
      - 'keda/**'
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cd to keda dir
        continue-on-error: true
        run: | 
          cd keda/
          if diff_text="$(diff --color -br --unified=0 $(ls|tail -2))" && [ $? -ne 1 ]; then
            echo "exit code of diff not 1"
            exit 1;
          fi;