name: version-diff
on: push
    
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create comment & show diff
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            one after the other
          reactions: eyes
        run: |
          cd keda/
          diff --color -bur $(ls | tail -2)