# # name: version-diff-advanced
# # on: pull_request
    
# # jobs:
# #   diff:
# #     name: Show diff
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v2

# #       - name: Diff
# #         id: diff-comment-id
# #         run: |
# #           cd keda/
# #           diff_text=""
# #           if diff_text="$(diff --color -br --unified=0 $(ls|tail -2))" && [ $? -ne 1 ]; then
# #             echo "exit code of diff not 1"
# #             exit 1;
# #           fi;
# #           PREFIX=$'<details>\n\n```diff\n\n'
# #           POSTFIX=$'\n\n```\n\n</details>'
# #           diff_text="${PREFIX}${diff_text}${POSTFIX}"
# #           diff_text="${diff_text//'%'/'%25'}"
# #           diff_text="${diff_text//$'\n'/'%0A'}"
# #           diff_text="${diff_text//$'\r'/'%0D'}"
# #           echo "$diff_text"
# #           echo "::set-output name=body::$diff_text"

# #       - name: Create comment
# #         uses: peter-evans/create-or-update-comment@v2
# #         with:
# #           issue-number: ${{ github.event.pull_request.number }}
# #           body: |
# #             tbc advanced
# #             ${{ steps.diff-comment-id.outputs.body }}
# #           reactions: rocket

name: git diff dynamic jobs
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir_old: ${{ steps.setup-id.outputs.dir_old }}
      dir_new: ${{ steps.setup-id.outputs.dir_new }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dirs for diff
        id: setup-id
        run: |
          cd keda/
          DIRS=$(ls|tail -2)
          dirs=($DIRS)
          dir_old_list=$(find ${dirs[0]} -print)
          dir_new_list=$(find ${dirs[1]} -print)

          echo $dir_old_list
          echo $dir_new_list
          echo "::set-output name=file_array::$file_array"

  # diff:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix: 
  #       old: github.steps.
  #       new: ["hola",]
        
    # needs: setup

    # name: Show diff
    # runs-on: ubuntu-latest

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2

    #   - name: setup for comment diff
    #     id: diff-comment-id
    #     run: |
    #       diff_text=$(git diff main...${GITHUB_REF##*/})
    #       echo "$diff_text"
    #       echo "::set-output name=body::$diff_text"

    #   - name: Create comment
    #     uses: peter-evans/create-or-update-comment@v2
    #     with:
    #       issue-number: ${{ github.event.pull_request.number }}
    #       body: |
    #         git diff of versions?
    #         ${{ steps.diff-comment-id.outputs.body }}
    #       reactions: rocket
      