name: git diff dynamic jobs
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir_old: ${{ steps.setup-id.outputs.dir_old }}
      dir_new: ${{ steps.setup-id.outputs.dir_new }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dirs for diff
        id: setup-id
        run: |
          cd keda/
          DIRS=$(ls|tail -2)
          dirs=($DIRS)
          dir_old_list=$(find ${dirs[0]} -print)
          dir_new_list=$(find ${dirs[1]} -print)
          root=$(pwd)

          dir_old="{\"old\":["
          for file in $dir_old_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              le=($dir_old_list)
              dir_old+="\"$file\""
              if [ "$file" != "${le[-1]}" ]; then
                dir_old+=","
              fi  
            fi
          done
          dir_old+="]}"

          dir_new="{\"new\":["
          for file in $dir_new_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              dir_new+="\"$file\""
              le=($dir_new_list)
              if [ "$file" != "${le[-1]}" ]; then
                dir_new+=","
              fi
            fi
          done
          dir_new+="]}"
          
          echo $dir_old
          echo "lalalal"
          echo $dir_new

          echo "::set-output name=dir_old::$dir_old"
          echo "::set-output name=dir_new::$dir_new"

  diff:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        old: ${{fromJSON(needs.setup.outputs.dir_old)}}
        new: ${{fromJSON(needs.setup.outputs.dir_new)}}
    needs: setup

    name: Show diff
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make diffs
        id: diff-id
        run: |
          echo ${{ matrix.old }}
          echo '\nseparator\n'

    #   - name: Create comment
    #     uses: peter-evans/create-or-update-comment@v2
    #     with:
    #       issue-number: ${{ github.event.pull_request.number }}
    #       body: |
    #         git diff of versions?
    #         ${{ steps.diff-comment-id.outputs.body }}
    #       reactions: rocket
      