name: git diff dynamic jobs
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      new_files: ${{ steps.setup-id.outputs.new_files }}
      old_files: ${{ steps.setup-id.outputs.old_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dirs for diff
        id: setup-id
        run: |
          cd keda/
          DIRS=$(ls|tail -2)
          dirs=($DIRS)
          dir_old_list=$(find ${dirs[0]} -print)
          dir_new_list=$(find ${dirs[1]} -print)
          root=$(pwd)

          for file in $dir_old_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              old_files="$old_files $file"
            fi
          done

          new_files+="{\"new\":["
          for file in $dir_new_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              new_files+="\"$file\""
              le=($dir_new_list)
              if [ "$file" != "${le[-1]}" ]; then
                new_files+=","
              fi
            fi
          done
          new_files+="]}"
          
          echo $old_files
          echo $new_files          

          echo "::set-output name=new_files::$new_files"
          echo "::set-output name=old_files::$old_files"

  diff:
    name: Diff files
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.new_files)}}

    env:
      of: ${{ needs.setup.outputs.old_files }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make diff ${{matrix.new}}
        id: diff-id
        run: |
          regex=$(echo ${{matrix.new}} | sed 's/\/.*//')
          echo ${{matrix.nf}}
          echo '---separator---\n'
          echo "hello"

    #   - name: Create comment
    #     uses: peter-evans/create-or-update-comment@v2
    #     with:
    #       issue-number: ${{ github.event.pull_request.number }}
    #       body: |
    #         git diff of versions?
    #         ${{ steps.diff-comment-id.outputs.body }}
    #       reactions: rocket
      