name: version-diff
on: 
  pull_request:
    paths: 
      - 'keda/**'
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cd to keda dir
        run: | 
          cd keda/
          diff --colors -br --unified=0 $(ls | tail -2)
