name: version-diff-side-by-side
on: push
    
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get-comment-body
        run: |
          cd keda/
          diff --color -bur $(ls | tail -2) > diff-side.out
          body="$(cat diff-side.out)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            I stand by your side

            ${{ steps.get-comment-body.outputs.body }}
          reactions: rocket
      