name: version-diff
on: 
  workflow_dispatch
    
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show diff
        run: |
          cd keda/
          diff -bur $(ls | tail -2)
