# # name: version-diff-advanced
# # on: pull_request
    
# # jobs:
# #   diff:
# #     name: Show diff
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v2

# #       - name: Diff
# #         id: diff-comment-id
# #         run: |
# #           cd keda/
# #           diff_text=""
# #           if diff_text="$(diff --color -br --unified=0 $(ls|tail -2))" && [ $? -ne 1 ]; then
# #             echo "exit code of diff not 1"
# #             exit 1;
# #           fi;
# #           PREFIX=$'<details>\n\n```diff\n\n'
# #           POSTFIX=$'\n\n```\n\n</details>'
# #           diff_text="${PREFIX}${diff_text}${POSTFIX}"
# #           diff_text="${diff_text//'%'/'%25'}"
# #           diff_text="${diff_text//$'\n'/'%0A'}"
# #           diff_text="${diff_text//$'\r'/'%0D'}"
# #           echo "$diff_text"
# #           echo "::set-output name=body::$diff_text"

# #       - name: Create comment
# #         uses: peter-evans/create-or-update-comment@v2
# #         with:
# #           issue-number: ${{ github.event.pull_request.number }}
# #           body: |
# #             tbc advanced
# #             ${{ steps.diff-comment-id.outputs.body }}
# #           reactions: rocket

name: git diff dynamic jobs
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir_old: ${{ steps.setup-id.outputs.dir_old }}
      dir_new: ${{ steps.setup-id.outputs.dir_new }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dirs for diff
        id: setup-id
        run: |
          cd keda/
          DIRS=$(ls|tail -2)
          dirs=($DIRS)
          dir_old_list=$(find ${dirs[0]} -print)
          dir_new_list=$(find ${dirs[1]} -print)
          root=$(pwd)
          for file in $dir_old_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              dir_old="$dir_old $file"
            fi
          done
          for file in $dir_new_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              dir_new="$dir_new $file"
            fi
          done
          dir_old=($dir_old)
          dir_new=($dir_new)
          echo "::set-output name=dir_old::$dir_old"
          echo "::set-output name=dir_new::$dir_new"

  diff:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        old: ${{needs.setup.outputs.dir_old}}
        new: ${{needs.setup.outputs.dir_new}}
    needs: setup

    name: Show diff
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make diffs
    #     id: diff-comment-id
        run: |
          echo ${{ matrix.old }}
          echo '\nseparator\n'
          echo "$new"

    #   - name: Create comment
    #     uses: peter-evans/create-or-update-comment@v2
    #     with:
    #       issue-number: ${{ github.event.pull_request.number }}
    #       body: |
    #         git diff of versions?
    #         ${{ steps.diff-comment-id.outputs.body }}
    #       reactions: rocket
      