name: version-diff-side-by-side
on: push
    
jobs:
  diff:
    name: Show diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create comment & show diff
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            I stand by your side
          reactions: rocket
        run: |
          cd keda/
          diff --color -byr $(ls | tail -2)
      