name: git diff dynamic jobs
on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dir_old: ${{ steps.setup-id.outputs.files_extracted }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dirs for diff
        id: setup-id
        run: |
          cd keda/
          DIRS=$(ls|tail -2)
          dirs=($DIRS)
          dir_old_list=$(find ${dirs[0]} -print)
          dir_new_list=$(find ${dirs[1]} -print)
          root=$(pwd)

          files_extracted="{\"old\":["
          for file in $dir_old_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              le=($dir_old_list)
              files_extracted+="\"$file\""
              if [ "$file" != "${le[-1]}" ]; then
                files_extracted+=","
              fi  
            fi
          done
          files_extracted+="],\"new\":["

          for file in $dir_new_list
          do 
            f=$root"/"$file
            if [ -f "$f" ]; then
              files_extracted+="\"$file\""
              le=($dir_new_list)
              if [ "$file" != "${le[-1]}" ]; then
                files_extracted+=","
              fi
            fi
          done
          files_extracted+="]}"
          
          echo $files_extracted

          echo "::set-output name=files_extracted::$files_extracted"

  diff:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.files_extracted)}}

    # name: Show diff
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: make diffs
        id: diff-id
        run: |
          echo ${{ matrix.old }}
          echo '\nseparator\n'

    #   - name: Create comment
    #     uses: peter-evans/create-or-update-comment@v2
    #     with:
    #       issue-number: ${{ github.event.pull_request.number }}
    #       body: |
    #         git diff of versions?
    #         ${{ steps.diff-comment-id.outputs.body }}
    #       reactions: rocket
      